### ISSUE TITLE
[etc.] Author와 Committer의 차이

### ISSUE THREAD

**Issue by blcklamb** [githru/githru-boot#33]
작일 온라인 미팅 중 궁금한 부분이 생겨 슬쩍 찾아보다가 흥미로운 반례를 발견하여 공유합니다.

![image](https://user-images.githubusercontent.com/92101831/181902837-d2b58de2-70dc-4fda-9c58-2d3a4db8bc9f.png)

보통의 경우라면 Author와 Committer는 동일하지만,

Github GUI에서 직접 작업하여 commit한 경우는 committer가 github로 할당됩니다.

별 건 아니지만... 그래도 다른 경우를 찾기 힘든 것 같아서 공유합니다! 🤸‍♂️

혹시나 다른 경우를 찾게 되신다면 또 공유부탁드립니다.

**Comment by anpaul0615** [comment]
위 내용을 wiki 에도 작성해봤습니다. (연습겸...ㅎㅎ)
