### ISSUE TITLE
데이터 조인 메소드 data() vs datum   (D3.js)

### ISSUE THREAD

**Issue by bishoe01** [githru/githru-boot#87]
# data() vs datum()
### datum() 작성 이유 
dautm이랑 비슷한 역할을 하는 데이터 조인 메소드라하면  data 나 enter 정도가 있을 것 같은데요!
enter는 새롭게 데이터를 입힐 때 사용하는것이니 제외하면 data랑 비교가 될 것 같습니다!  
일단은 path를 그려줄 때는 datum을 사용해주는게 좋다고 구글링하다가 알게되었습니다.

[data() vs datum](https://www.intothevoid.io/data-visualization/understanding-d3-data-vs-datum/) 

대상 요소에 datum()은 단일 데이터/그룹을 연결해주는 것이고 data는 데이터 세트를 연결해주기 때문에,
현재 data의 구조가 array하나로 이루어져있어서 datum을 써줬습니다. 
아마 현재 구조에서 data()를 써주려면은 파라미터값이 
data(data)가 아니라 data([data]) 이렇게 여러 요소를 포함한 배열의 형식으로 보내주는 형태가 될 것 같습니다. 
[data vs data](https://stackoverflow.com/questions/13728402/what-is-the-difference-d3-datum-vs-data)

data()를 사용해주려면 다음과 같은 코드가 될 것 같습니다! 
### data()를 사용했을 때 코드 
  ```
svg
        .selectAll("path")
        .data([data]) // Wrap data array in another array
        .join("path")
        .transition()
        .duration(1000)
        .attr("fill", "none")
        .attr("stroke", crimeTypeColors[currentCrimeType])
        .attr("stroke-width", 1.5)
        .attr("d", line);
```
### datum()를 사용했을 때 코드  ( 기존 ) 
```
 svg
        .append("path")
        .datum(data)
        .transition()
        .duration(1000)
        .attr("fill", "none")
        .attr("stroke", crimeTypeColors[currentCrimeType])
        .attr("stroke-width", 1.5)
        .attr("d", line);

```

_Originally posted by @bishoe01 in https://github.com/githru/githru-boot/pull/74#discussion_r1268236359_

**Comment by KyuTae98** [comment]
이렇게 정리도 해주셨네요!! 감사합니다!!!

**Comment by 2taesung** [comment]
datum 이라는 키워드에대해 제대로 알게 됐네요! 감사합니다!!!
